# -*- coding: utf-8 -*-
"""미니프로젝트 과제 최종본.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAfaVww6x68bXfB29XBLV7Lvs8F1s9Cj
"""

!git clone https://github.com/WegraLee/deep-learning-from-scratch.git

import sys
import os

sys.path.append('/content/deep-learning-from-scratch')

import numpy as np
import matplotlib.pyplot as plt

from common.trainer import Trainer
from ch07.simple_convnet import SimpleConvNet

!mkdir -p fashion_mnist

!wget -P fashion_mnist http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-images-idx3-ubyte.gz
!wget -P fashion_mnist http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-labels-idx1-ubyte.gz
!wget -P fashion_mnist http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
!wget -P fashion_mnist http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-labels-idx1-ubyte.gz

import gzip

def load_images(file_path):
    with gzip.open(file_path, 'rb') as f:
        data = np.frombuffer(f.read(), np.uint8, offset=16)
    data = data.reshape(-1, 1, 28, 28)
    data = data.astype(np.float32) / 255.0
    return data

def load_labels(file_path):
    with gzip.open(file_path, 'rb') as f:
        labels = np.frombuffer(f.read(), np.uint8, offset=8)
    return labels

x_train = load_images('./fashion_mnist/train-images-idx3-ubyte.gz')
t_train = load_labels('./fashion_mnist/train-labels-idx1-ubyte.gz')

x_test = load_images('./fashion_mnist/t10k-images-idx3-ubyte.gz')
t_test = load_labels('./fashion_mnist/t10k-labels-idx1-ubyte.gz')

print(x_train.shape, t_train.shape)
print(x_test.shape, t_test.shape)

import numpy as np
from collections import OrderedDict
from common.layers import *
from common.trainer import Trainer

import numpy as np
from collections import OrderedDict
import matplotlib.pyplot as plt

from common.layers import Convolution, Relu, Pooling, Affine, SoftmaxWithLoss
from common.trainer import Trainer


class TwoConvNet:
    def __init__(self):
        self.params = {}

        self.params['W1'] = np.sqrt(2 / (1 * 3 * 3)) * np.random.randn(32, 1, 3, 3)
        self.params['b1'] = np.zeros(32)

        self.params['W2'] = np.sqrt(2 / (32 * 3 * 3)) * np.random.randn(64, 32, 3, 3)
        self.params['b2'] = np.zeros(64)

        self.params['W3'] = np.sqrt(2 / (64 * 7 * 7)) * np.random.randn(64 * 7 * 7, 256)
        self.params['b3'] = np.zeros(256)

        self.params['W4'] = np.sqrt(2 / 256) * np.random.randn(256, 10)
        self.params['b4'] = np.zeros(10)

        self.layers = OrderedDict()

        self.layers['Conv1'] = Convolution(self.params['W1'], self.params['b1'], stride=1, pad=1)
        self.layers['Relu1'] = Relu()
        self.layers['Pool1'] = Pooling(pool_h=2, pool_w=2, stride=2)

        self.layers['Conv2'] = Convolution(self.params['W2'], self.params['b2'], stride=1, pad=1)
        self.layers['Relu2'] = Relu()
        self.layers['Pool2'] = Pooling(pool_h=2, pool_w=2, stride=2)

        self.layers['Affine1'] = Affine(self.params['W3'], self.params['b3'])
        self.layers['Relu3'] = Relu()
        self.layers['Affine2'] = Affine(self.params['W4'], self.params['b4'])

        self.last_layer = SoftmaxWithLoss()

    def predict(self, x):
        for layer in self.layers.values():
            x = layer.forward(x)
        return x

    def loss(self, x, t):
        y = self.predict(x)
        return self.last_layer.forward(y, t)

    def accuracy(self, x, t, batch_size=100):
        if t.ndim != 1:
            t = np.argmax(t, axis=1)

        acc = 0.0

        for i in range(int(x.shape[0] / batch_size)):
            tx = x[i * batch_size:(i + 1) * batch_size]
            tt = t[i * batch_size:(i + 1) * batch_size]

            y = self.predict(tx)
            y = np.argmax(y, axis=1)

            acc += np.sum(y == tt)

        return acc / x.shape[0]

    def gradient(self, x, t):
        self.loss(x, t)

        dout = 1
        dout = self.last_layer.backward(dout)

        layers = list(self.layers.values())
        layers.reverse()

        for layer in layers:
            dout = layer.backward(dout)

        grads = {}
        grads['W1'] = self.layers['Conv1'].dW
        grads['b1'] = self.layers['Conv1'].db
        grads['W2'] = self.layers['Conv2'].dW
        grads['b2'] = self.layers['Conv2'].db
        grads['W3'] = self.layers['Affine1'].dW
        grads['b3'] = self.layers['Affine1'].db
        grads['W4'] = self.layers['Affine2'].dW
        grads['b4'] = self.layers['Affine2'].db

        return grads


network = TwoConvNet()

trainer = Trainer(
    network,
    x_train,
    t_train,
    x_test,
    t_test,
    epochs=15,
    mini_batch_size=100,
    optimizer='Adam',
    optimizer_param={'lr': 0.0005},
    evaluate_sample_num_per_epoch=1000
)

trainer.train()


train_acc = network.accuracy(x_train, t_train)
test_acc = network.accuracy(x_test, t_test)

print("================================")
print(f"Final Train Accuracy: {train_acc * 100:.2f}%")
print(f"Final Test Accuracy: {test_acc * 100:.2f}%")
print("================================")


plt.figure(figsize=(8, 5))

plt.plot(
    np.arange(1, len(trainer.train_acc_list) + 1),
    trainer.train_acc_list,
    marker='o',
    label='Train Accuracy'
)

plt.plot(
    np.arange(1, len(trainer.test_acc_list) + 1),
    trainer.test_acc_list,
    marker='s',
    label='Test Accuracy'
)

plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Fashion-MNIST CNN Accuracy Curve')
plt.legend()
plt.grid(True)
plt.show()